// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://tableflow.com/terms",
        "contact": {
            "name": "TableFlow",
            "url": "https://tableflow.com",
            "email": "support@tableflow.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/v1/import/{id}": {
            "get": {
                "description": "Get a single import",
                "tags": [
                    "Import"
                ],
                "summary": "Get import",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Import ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Import"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/admin/v1/importer": {
            "post": {
                "description": "Create an importer",
                "tags": [
                    "Importer"
                ],
                "summary": "Create importer",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ImporterCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Importer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/admin/v1/importer/{id}": {
            "get": {
                "description": "Get a single importer",
                "tags": [
                    "Importer"
                ],
                "summary": "Get importer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Importer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Importer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            },
            "post": {
                "description": "Edit an importer",
                "tags": [
                    "Importer"
                ],
                "summary": "Edit importer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Importer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ImporterEditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Importer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an importer",
                "tags": [
                    "Importer"
                ],
                "summary": "Delete importer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Importer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/admin/v1/importers/{workspace-id}": {
            "get": {
                "description": "Get a list of importers",
                "tags": [
                    "Importer"
                ],
                "summary": "Get importers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Importer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/admin/v1/imports/{workspace-id}": {
            "get": {
                "description": "Get a list of imports",
                "tags": [
                    "Import"
                ],
                "summary": "Get imports",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Import"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/admin/v1/organization-workspaces": {
            "get": {
                "description": "Get the current user's organization and workspaces that are a part of the organization",
                "tags": [
                    "Organization"
                ],
                "summary": "Get organization and attached workspaces",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Organization"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/admin/v1/template-column": {
            "post": {
                "description": "Create a template column",
                "tags": [
                    "Template"
                ],
                "summary": "Create template column",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.TemplateColumnCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Template"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/admin/v1/template-column/{id}": {
            "post": {
                "description": "Edit a template column",
                "tags": [
                    "Template"
                ],
                "summary": "Edit template column",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template column ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.TemplateColumnEditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Template"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a template column",
                "tags": [
                    "Template"
                ],
                "summary": "Delete template column",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template column ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Template"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/admin/v1/template/{id}": {
            "get": {
                "description": "Get a single template",
                "tags": [
                    "Template"
                ],
                "summary": "Get template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Template"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/admin/v1/upload/{id}": {
            "get": {
                "description": "Get a single upload",
                "tags": [
                    "Upload"
                ],
                "summary": "Get upload",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Upload ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Upload"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/admin/v1/workspace/{id}/api-key": {
            "get": {
                "description": "Get the current API key of a workspace",
                "tags": [
                    "Workspace"
                ],
                "summary": "Get workspace API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            },
            "post": {
                "description": "Regenerate the current API key of a workspace and return the new API key",
                "tags": [
                    "Workspace"
                ],
                "summary": "Regenerate workspace API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/file-import/v1/files": {
            "post": {
                "description": "Creates a new file upload after validating the length and parsing the metadata",
                "tags": [
                    "File Import"
                ],
                "summary": "Post file (tus)",
                "responses": {}
            }
        },
        "/file-import/v1/files/{id}": {
            "head": {
                "description": "Returns the length and offset for the HEAD request",
                "tags": [
                    "File Import"
                ],
                "summary": "Head file (tus)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tus file ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "patch": {
                "description": "Adds a chunk to an upload, only allowed if enough space in the upload is left",
                "tags": [
                    "File Import"
                ],
                "summary": "Patch file (tus)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tus file ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/file-import/v1/import/{id}": {
            "get": {
                "description": "Get a single import by the upload ID, including the data if the import is complete",
                "tags": [
                    "File Import"
                ],
                "summary": "Get import by upload ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Upload ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ImportServiceImport"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/file-import/v1/importer/{id}": {
            "get": {
                "description": "Get a single importer and its template",
                "tags": [
                    "File Import"
                ],
                "summary": "Get importer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Importer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ImportServiceImporter"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            },
            "post": {
                "description": "Get a single importer and its template",
                "tags": [
                    "File Import"
                ],
                "summary": "Get importer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Importer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ImportServiceImporter"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/file-import/v1/upload/{id}": {
            "get": {
                "description": "Get a single upload by the tus ID provided to the client from the upload",
                "tags": [
                    "File Import"
                ],
                "summary": "Get upload by tus ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tus ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ImportServiceUpload"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/file-import/v1/upload/{id}/set-column-mapping": {
            "post": {
                "description": "Set the template column IDs for each upload column and trigger the import. Note: we will eventually have a separate import endpoint once there is a review step in the upload process.",
                "tags": [
                    "File Import"
                ],
                "summary": "Set upload column mapping and import data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Upload ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/file-import/v1/upload/{id}/set-header-row": {
            "post": {
                "description": "Set the header row index on the upload",
                "tags": [
                    "File Import"
                ],
                "summary": "Set upload header row",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Upload ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.ImporterServiceUploadHeaderRowSelection"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ImportServiceUpload"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/public/health": {
            "get": {
                "description": "Health check",
                "tags": [
                    "Public"
                ],
                "summary": "Health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/v1/import/{id}": {
            "get": {
                "description": "Get an individual import",
                "tags": [
                    "External API"
                ],
                "summary": "Get import",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Import ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Import"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/v1/import/{id}/download": {
            "get": {
                "description": "Download the import as a file",
                "tags": [
                    "External API"
                ],
                "summary": "Download import",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Import ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/v1/import/{id}/rows": {
            "get": {
                "description": "Paginate the rows of an import",
                "tags": [
                    "External API"
                ],
                "summary": "Get import rows",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Import ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "maximum": 1000,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Pagination limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.ImportRow"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Import": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1682366228
                },
                "id": {
                    "type": "string",
                    "example": "da5554e3-6c87-41b2-9366-5449a2f15b53"
                },
                "importer_id": {
                    "type": "string",
                    "example": "6de452a2-bd1f-4cb3-b29b-0f8a2e3d9353"
                },
                "is_stored": {
                    "type": "boolean",
                    "example": false
                },
                "metadata": {
                    "$ref": "#/definitions/model.JSONB"
                },
                "num_columns": {
                    "type": "integer",
                    "example": 8
                },
                "num_processed_values": {
                    "type": "integer",
                    "example": 128
                },
                "num_rows": {
                    "type": "integer",
                    "example": 256
                },
                "upload_id": {
                    "type": "string",
                    "example": "50ca61e1-f683-4b03-9ec4-4b3adb592bf1"
                },
                "workspace_id": {
                    "type": "string",
                    "example": "b2079476-261a-41fe-8019-46eb51c537f7"
                }
            }
        },
        "model.Importer": {
            "type": "object",
            "properties": {
                "allowed_domains": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "example.com"
                    ]
                },
                "created_at": {
                    "type": "integer",
                    "example": 1682366228
                },
                "created_by": {
                    "$ref": "#/definitions/model.User"
                },
                "id": {
                    "type": "string",
                    "example": "6de452a2-bd1f-4cb3-b29b-0f8a2e3d9353"
                },
                "name": {
                    "type": "string",
                    "example": "Test Importer"
                },
                "skip_header_row_selection": {
                    "type": "boolean",
                    "example": false
                },
                "template": {
                    "$ref": "#/definitions/model.Template"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1682366228
                },
                "updated_by": {
                    "$ref": "#/definitions/model.User"
                },
                "webhooks_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "workspace_id": {
                    "type": "string",
                    "example": "b2079476-261a-41fe-8019-46eb51c537f7"
                }
            }
        },
        "model.JSONB": {
            "type": "object",
            "additionalProperties": true
        },
        "model.Organization": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1682366228
                },
                "created_by": {
                    "$ref": "#/definitions/model.User"
                },
                "id": {
                    "type": "string",
                    "example": "8a7850a1-8b03-4337-a530-f9d48f7d9232"
                },
                "name": {
                    "type": "string",
                    "example": "My Organization"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1682366228
                },
                "updated_by": {
                    "$ref": "#/definitions/model.User"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.User"
                    }
                },
                "workspaces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Workspace"
                    }
                }
            }
        },
        "model.Template": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1682366228
                },
                "created_by": {
                    "$ref": "#/definitions/model.User"
                },
                "id": {
                    "type": "string",
                    "example": "f0797968-becc-422a-b135-19de1d8c5d46"
                },
                "importer_id": {
                    "type": "string",
                    "example": "6de452a2-bd1f-4cb3-b29b-0f8a2e3d9353"
                },
                "name": {
                    "type": "string",
                    "example": "My Template"
                },
                "template_columns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TemplateColumn"
                    }
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1682366228
                },
                "updated_by": {
                    "$ref": "#/definitions/model.User"
                },
                "workspace_id": {
                    "type": "string",
                    "example": "b2079476-261a-41fe-8019-46eb51c537f7"
                }
            }
        },
        "model.TemplateColumn": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1682366228
                },
                "created_by": {
                    "$ref": "#/definitions/model.User"
                },
                "description": {
                    "type": "string",
                    "example": "An email address"
                },
                "id": {
                    "type": "string",
                    "example": "a1ed136d-33ce-4b7e-a7a4-8a5ccfe54cd5"
                },
                "key": {
                    "type": "string",
                    "example": "email"
                },
                "name": {
                    "type": "string",
                    "example": "Email"
                },
                "required": {
                    "type": "boolean",
                    "example": false
                },
                "template_id": {
                    "type": "string",
                    "example": "f0797968-becc-422a-b135-19de1d8c5d46"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1682366228
                },
                "updated_by": {
                    "$ref": "#/definitions/model.User"
                }
            }
        },
        "model.Upload": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1682366228
                },
                "file_extension": {
                    "type": "string",
                    "example": "csv"
                },
                "file_name": {
                    "type": "string",
                    "example": "example.csv"
                },
                "file_size": {
                    "type": "integer",
                    "example": 1024
                },
                "file_type": {
                    "type": "string",
                    "example": "text/csv"
                },
                "header_row_index": {
                    "type": "integer",
                    "example": 0
                },
                "id": {
                    "type": "string",
                    "example": "50ca61e1-f683-4b03-9ec4-4b3adb592bf1"
                },
                "importer_id": {
                    "type": "string",
                    "example": "6de452a2-bd1f-4cb3-b29b-0f8a2e3d9353"
                },
                "is_stored": {
                    "type": "boolean",
                    "example": false
                },
                "metadata": {
                    "type": "string",
                    "example": "{\"user_id\": 1234}"
                },
                "num_columns": {
                    "type": "integer",
                    "example": 8
                },
                "num_rows": {
                    "type": "integer",
                    "example": 256
                },
                "template": {
                    "description": "Set if the user passes in a template to the SDK, which overrides the template on the importer",
                    "type": "string",
                    "example": "{}"
                },
                "tus_id": {
                    "type": "string",
                    "example": "ee715c254ee61855b465ed61be930487"
                },
                "upload_columns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.UploadColumn"
                    }
                },
                "workspace_id": {
                    "type": "string",
                    "example": "b2079476-261a-41fe-8019-46eb51c537f7"
                }
            }
        },
        "model.UploadColumn": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "3c79e7fd-1018-4a27-8b86-9cee84221cd8"
                },
                "index": {
                    "type": "integer",
                    "example": 0
                },
                "name": {
                    "type": "string",
                    "example": "Work Email"
                },
                "sample_data": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "test@example.com"
                    ]
                },
                "template_column_id": {
                    "type": "string",
                    "example": "a1ed136d-33ce-4b7e-a7a4-8a5ccfe54cd5"
                },
                "upload_id": {
                    "type": "string",
                    "example": "50ca61e1-f683-4b03-9ec4-4b3adb592bf1"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "test@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "249ac073-0fe8-4705-82ff-73e3df491b04"
                },
                "recipe": {
                    "type": "string",
                    "example": "github"
                },
                "role": {
                    "type": "string",
                    "example": "user"
                },
                "time_joined": {
                    "type": "integer",
                    "example": 1682366228
                }
            }
        },
        "model.Workspace": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1682366228
                },
                "created_by": {
                    "$ref": "#/definitions/model.User"
                },
                "id": {
                    "type": "string",
                    "example": "b2079476-261a-41fe-8019-46eb51c537f7"
                },
                "name": {
                    "type": "string",
                    "example": "My Workspace"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1682366228
                },
                "updated_by": {
                    "$ref": "#/definitions/model.User"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.User"
                    }
                }
            }
        },
        "types.ImportRow": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "integer",
                    "example": 0
                },
                "values": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "types.ImportServiceImport": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1682366228
                },
                "id": {
                    "type": "string",
                    "example": "da5554e3-6c87-41b2-9366-5449a2f15b53"
                },
                "importer_id": {
                    "type": "string",
                    "example": "6de452a2-bd1f-4cb3-b29b-0f8a2e3d9353"
                },
                "is_stored": {
                    "type": "boolean",
                    "example": false
                },
                "metadata": {
                    "$ref": "#/definitions/model.JSONB"
                },
                "num_columns": {
                    "type": "integer",
                    "example": 8
                },
                "num_processed_values": {
                    "type": "integer",
                    "example": 128
                },
                "num_rows": {
                    "type": "integer",
                    "example": 256
                },
                "rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ImportRow"
                    }
                },
                "upload_id": {
                    "type": "string",
                    "example": "50ca61e1-f683-4b03-9ec4-4b3adb592bf1"
                }
            }
        },
        "types.ImportServiceImporter": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "6de452a2-bd1f-4cb3-b29b-0f8a2e3d9353"
                },
                "name": {
                    "type": "string",
                    "example": "Test Importer"
                },
                "skip_header_row_selection": {
                    "type": "boolean",
                    "example": false
                },
                "template": {
                    "$ref": "#/definitions/types.ImportServiceTemplate"
                }
            }
        },
        "types.ImportServiceTemplate": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ImportServiceTemplateColumn"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "f0797968-becc-422a-b135-19de1d8c5d46"
                },
                "name": {
                    "type": "string",
                    "example": "My Template"
                }
            }
        },
        "types.ImportServiceTemplateColumn": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "The first name"
                },
                "id": {
                    "type": "string",
                    "example": "a1ed136d-33ce-4b7e-a7a4-8a5ccfe54cd5"
                },
                "key": {
                    "type": "string",
                    "example": "email"
                },
                "name": {
                    "type": "string",
                    "example": "First Name"
                },
                "required": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "types.ImportServiceUpload": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1682366228
                },
                "file_extension": {
                    "type": "string",
                    "example": "csv"
                },
                "file_name": {
                    "type": "string",
                    "example": "example.csv"
                },
                "file_size": {
                    "type": "integer",
                    "example": 1024
                },
                "file_type": {
                    "type": "string",
                    "example": "text/csv"
                },
                "header_row_index": {
                    "type": "integer",
                    "example": 0
                },
                "id": {
                    "type": "string",
                    "example": "50ca61e1-f683-4b03-9ec4-4b3adb592bf1"
                },
                "importer_id": {
                    "type": "string",
                    "example": "6de452a2-bd1f-4cb3-b29b-0f8a2e3d9353"
                },
                "is_stored": {
                    "type": "boolean",
                    "example": false
                },
                "metadata": {
                    "type": "string",
                    "example": "{\"user_id\": 1234}"
                },
                "template": {
                    "description": "Set if the user passes in a template to the SDK, which overrides the template on the importer",
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.ImportServiceTemplate"
                        }
                    ]
                },
                "tus_id": {
                    "type": "string",
                    "example": "ee715c254ee61855b465ed61be930487"
                },
                "upload_columns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ImportServiceUploadColumn"
                    }
                },
                "upload_rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.UploadRow"
                    }
                }
            }
        },
        "types.ImportServiceUploadColumn": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "3c79e7fd-1018-4a27-8b86-9cee84221cd8"
                },
                "index": {
                    "type": "integer",
                    "example": 0
                },
                "name": {
                    "type": "string",
                    "example": "Work Email"
                },
                "sample_data": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "test@example.com"
                    ]
                }
            }
        },
        "types.ImporterServiceUploadHeaderRowSelection": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "types.Res": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "types.UploadRow": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "integer",
                    "example": 0
                },
                "values": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "web.ImporterCreateRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Test Importer"
                },
                "workspace_id": {
                    "type": "string",
                    "example": "b2079476-261a-41fe-8019-46eb51c537f7"
                }
            }
        },
        "web.ImporterEditRequest": {
            "type": "object",
            "properties": {
                "allowed_domains": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "example.com"
                    ]
                },
                "name": {
                    "type": "string",
                    "example": "Test Importer"
                },
                "skip_header_row_selection": {
                    "type": "boolean",
                    "example": false
                },
                "webhooks_enabled": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "web.TemplateColumnCreateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "The first name"
                },
                "key": {
                    "type": "string",
                    "example": "first_name"
                },
                "name": {
                    "type": "string",
                    "example": "First Name"
                },
                "required": {
                    "type": "boolean",
                    "example": false
                },
                "template_id": {
                    "type": "string",
                    "example": "f0797968-becc-422a-b135-19de1d8c5d46"
                }
            }
        },
        "web.TemplateColumnEditRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "The first name"
                },
                "key": {
                    "type": "string",
                    "example": "first_name"
                },
                "name": {
                    "type": "string",
                    "example": "First Name"
                },
                "required": {
                    "type": "boolean",
                    "example": false
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.2",
	Host:             "localhost:3003",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "TableFlow API",
	Description:      "The backend API of the TableFlow application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
