// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://tableflow.com/terms",
        "contact": {
            "name": "TableFlow",
            "url": "https://tableflow.com",
            "email": "support@tableflow.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/file-import/v1/files": {
            "post": {
                "description": "Creates a new file upload after validating the length and parsing the metadata",
                "tags": [
                    "File Import"
                ],
                "summary": "Post file (tus)",
                "responses": {}
            }
        },
        "/file-import/v1/files/{id}": {
            "head": {
                "description": "Returns the length and offset for the HEAD request",
                "tags": [
                    "File Import"
                ],
                "summary": "Head file (tus)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tus file ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "patch": {
                "description": "Adds a chunk to an upload, only allowed if enough space in the upload is left",
                "tags": [
                    "File Import"
                ],
                "summary": "Patch file (tus)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tus file ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/file-import/v1/import/{id}/cell/edit": {
            "post": {
                "description": "Edit the value in a cell for an import. If the cell contains an error, it will run it through the validation before allowing the edit.",
                "tags": [
                    "File Import"
                ],
                "summary": "Edit a cell in an import",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Upload ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.ImportCell"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ImportCellEditResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/file-import/v1/import/{id}/review": {
            "get": {
                "description": "Get a single import by the upload ID, including the row data for the first page of the review screen if the import is complete",
                "tags": [
                    "File Import"
                ],
                "summary": "Get import by upload ID for the review screen",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Upload ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Import"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/file-import/v1/import/{id}/rows": {
            "get": {
                "description": "Paginate import rows by the upload ID of an import",
                "tags": [
                    "File Import"
                ],
                "summary": "Get import rows by upload ID for the review screen",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Upload ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 1000,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Pagination limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "all",
                            "valid",
                            "error"
                        ],
                        "type": "string",
                        "description": "Pagination filter",
                        "name": "filter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ImportData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/file-import/v1/import/{id}/submit": {
            "post": {
                "description": "Submit the reviewed import by the upload ID once the data is reviewed and any errors are fixed",
                "tags": [
                    "File Import"
                ],
                "summary": "Submit an import by upload ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Upload ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Import"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/file-import/v1/importer": {
            "post": {
                "description": "Get a single importer",
                "tags": [
                    "File Import"
                ],
                "summary": "Get importer",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Importer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/file-import/v1/upload/{id}": {
            "get": {
                "description": "Get a single upload by the tus ID provided to the client from the upload",
                "tags": [
                    "File Import"
                ],
                "summary": "Get upload by tus ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tus ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Upload"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/file-import/v1/upload/{id}/set-column-mapping": {
            "post": {
                "description": "Set the template column IDs for each upload column and trigger the import",
                "tags": [
                    "File Import"
                ],
                "summary": "Set upload column mapping and import data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Upload ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/file-import/v1/upload/{id}/set-header-row": {
            "post": {
                "description": "Set the header row index on the upload",
                "tags": [
                    "File Import"
                ],
                "summary": "Set upload header row",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Upload ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UploadHeaderRowSelection"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Upload"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        },
        "/public/health": {
            "get": {
                "description": "Health check",
                "tags": [
                    "Public"
                ],
                "summary": "Health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Res"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "jsonb.JSONB": {
            "type": "object",
            "properties": {
                "data": {},
                "valid": {
                    "description": "Valid is false if Data is NULL",
                    "type": "boolean"
                }
            }
        },
        "types.Import": {
            "type": "object",
            "properties": {
                "has_errors": {
                    "type": "boolean",
                    "example": false
                },
                "id": {
                    "type": "string",
                    "example": "da5554e3-6c87-41b2-9366-5449a2f15b53"
                },
                "is_stored": {
                    "type": "boolean",
                    "example": false
                },
                "metadata": {
                    "$ref": "#/definitions/jsonb.JSONB"
                },
                "num_columns": {
                    "type": "integer",
                    "example": 8
                },
                "num_error_rows": {
                    "type": "integer",
                    "example": 32
                },
                "num_processed_values": {
                    "type": "integer",
                    "example": 128
                },
                "num_rows": {
                    "type": "integer",
                    "example": 256
                },
                "num_valid_rows": {
                    "type": "integer",
                    "example": 224
                },
                "rows": {
                    "description": "Used for the final step in the onComplete",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ImportRowResponse"
                    }
                },
                "upload_id": {
                    "type": "string",
                    "example": "50ca61e1-f683-4b03-9ec4-4b3adb592bf1"
                }
            }
        },
        "types.ImportCell": {
            "type": "object",
            "properties": {
                "cell_key": {
                    "type": "string",
                    "example": "first_name"
                },
                "cell_value": {
                    "type": "string",
                    "example": "Laura"
                },
                "row_index": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "types.ImportCellEditResponse": {
            "type": "object",
            "properties": {
                "has_errors": {
                    "type": "boolean",
                    "example": false
                },
                "num_error_rows": {
                    "type": "integer",
                    "example": 32
                },
                "num_rows": {
                    "type": "integer",
                    "example": 256
                },
                "num_valid_rows": {
                    "type": "integer",
                    "example": 224
                },
                "row": {
                    "$ref": "#/definitions/types.ImportRow"
                }
            }
        },
        "types.ImportData": {
            "type": "object",
            "properties": {
                "filter": {
                    "type": "string"
                },
                "pagination": {
                    "$ref": "#/definitions/types.Pagination"
                },
                "rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ImportRow"
                    }
                }
            }
        },
        "types.ImportRow": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/types.ImportRowError"
                        }
                    }
                },
                "index": {
                    "type": "integer",
                    "example": 0
                },
                "values": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "types.ImportRowError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                },
                "validate": {
                    "type": "string"
                }
            }
        },
        "types.ImportRowResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/types.ImportRowError"
                        }
                    }
                },
                "index": {
                    "type": "integer",
                    "example": 0
                },
                "values": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "types.Importer": {
            "type": "object",
            "properties": {
                "template": {
                    "$ref": "#/definitions/types.Template"
                }
            }
        },
        "types.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "next_offset": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "types.Res": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "types.Template": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.TemplateColumn"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "f0797968-becc-422a-b135-19de1d8c5d46"
                }
            }
        },
        "types.TemplateColumn": {
            "type": "object",
            "properties": {
                "data_type": {
                    "type": "string",
                    "example": "string"
                },
                "description": {
                    "type": "string",
                    "example": "The first name"
                },
                "id": {
                    "type": "string",
                    "example": "a1ed136d-33ce-4b7e-a7a4-8a5ccfe54cd5"
                },
                "key": {
                    "type": "string",
                    "example": "email"
                },
                "name": {
                    "type": "string",
                    "example": "First Name"
                },
                "required": {
                    "type": "boolean",
                    "example": false
                },
                "suggested_mappings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "first_name"
                    ]
                },
                "validations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Validation"
                    }
                }
            }
        },
        "types.Upload": {
            "type": "object",
            "properties": {
                "file_extension": {
                    "type": "string",
                    "example": "csv"
                },
                "file_name": {
                    "type": "string",
                    "example": "example.csv"
                },
                "file_size": {
                    "type": "integer",
                    "example": 1024
                },
                "file_type": {
                    "type": "string",
                    "example": "text/csv"
                },
                "header_row_index": {
                    "type": "integer",
                    "example": 0
                },
                "id": {
                    "type": "string",
                    "example": "50ca61e1-f683-4b03-9ec4-4b3adb592bf1"
                },
                "is_stored": {
                    "type": "boolean",
                    "example": false
                },
                "matched_header_row_index": {
                    "type": "integer",
                    "example": 0
                },
                "metadata": {
                    "type": "string",
                    "example": "{\"user_id\": 1234}"
                },
                "sheet_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Sheet 1"
                    ]
                },
                "template": {
                    "description": "Set from the template provided in the SDK",
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Template"
                        }
                    ]
                },
                "tus_id": {
                    "type": "string",
                    "example": "ee715c254ee61855b465ed61be930487"
                },
                "upload_columns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.UploadColumn"
                    }
                },
                "upload_rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.UploadRow"
                    }
                }
            }
        },
        "types.UploadColumn": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "3c79e7fd-1018-4a27-8b86-9cee84221cd8"
                },
                "index": {
                    "type": "integer",
                    "example": 0
                },
                "name": {
                    "type": "string",
                    "example": "Work Email"
                },
                "sample_data": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "test@example.com"
                    ]
                },
                "suggested_template_column_id": {
                    "type": "string",
                    "example": "a1ed136d-33ce-4b7e-a7a4-8a5ccfe54cd5"
                }
            }
        },
        "types.UploadHeaderRowSelection": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "types.UploadRow": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "integer",
                    "example": 0
                },
                "values": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "types.Validation": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 4581
                },
                "message": {
                    "type": "string",
                    "example": "The cell must contain a value"
                },
                "options": {
                    "type": "string",
                    "example": "true"
                },
                "severity": {
                    "type": "string",
                    "example": "error"
                },
                "validate": {
                    "type": "string",
                    "example": "not_blank"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.2",
	Host:             "localhost:3003",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "TableFlow File Import API",
	Description:      "The backend file import API of the TableFlow application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
