// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: go/protos/column_matcher.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ColumnMatcherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateHeaders []string `protobuf:"bytes,1,rep,name=template_headers,json=templateHeaders,proto3" json:"template_headers,omitempty"`
	CsvHeaders      []string `protobuf:"bytes,2,rep,name=csv_headers,json=csvHeaders,proto3" json:"csv_headers,omitempty"`
}

func (x *ColumnMatcherRequest) Reset() {
	*x = ColumnMatcherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_protos_column_matcher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnMatcherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnMatcherRequest) ProtoMessage() {}

func (x *ColumnMatcherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_protos_column_matcher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnMatcherRequest.ProtoReflect.Descriptor instead.
func (*ColumnMatcherRequest) Descriptor() ([]byte, []int) {
	return file_go_protos_column_matcher_proto_rawDescGZIP(), []int{0}
}

func (x *ColumnMatcherRequest) GetTemplateHeaders() []string {
	if x != nil {
		return x.TemplateHeaders
	}
	return nil
}

func (x *ColumnMatcherRequest) GetCsvHeaders() []string {
	if x != nil {
		return x.CsvHeaders
	}
	return nil
}

type MatchedColumn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateColumn string `protobuf:"bytes,1,opt,name=template_column,json=templateColumn,proto3" json:"template_column,omitempty"`
	CsvColumn      string `protobuf:"bytes,2,opt,name=csv_column,json=csvColumn,proto3" json:"csv_column,omitempty"`
}

func (x *MatchedColumn) Reset() {
	*x = MatchedColumn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_protos_column_matcher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchedColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchedColumn) ProtoMessage() {}

func (x *MatchedColumn) ProtoReflect() protoreflect.Message {
	mi := &file_go_protos_column_matcher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchedColumn.ProtoReflect.Descriptor instead.
func (*MatchedColumn) Descriptor() ([]byte, []int) {
	return file_go_protos_column_matcher_proto_rawDescGZIP(), []int{1}
}

func (x *MatchedColumn) GetTemplateColumn() string {
	if x != nil {
		return x.TemplateColumn
	}
	return ""
}

func (x *MatchedColumn) GetCsvColumn() string {
	if x != nil {
		return x.CsvColumn
	}
	return ""
}

type ColumnMatcherResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchedColumns []*MatchedColumn `protobuf:"bytes,1,rep,name=matched_columns,json=matchedColumns,proto3" json:"matched_columns,omitempty"`
}

func (x *ColumnMatcherResponse) Reset() {
	*x = ColumnMatcherResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_protos_column_matcher_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnMatcherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnMatcherResponse) ProtoMessage() {}

func (x *ColumnMatcherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_protos_column_matcher_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnMatcherResponse.ProtoReflect.Descriptor instead.
func (*ColumnMatcherResponse) Descriptor() ([]byte, []int) {
	return file_go_protos_column_matcher_proto_rawDescGZIP(), []int{2}
}

func (x *ColumnMatcherResponse) GetMatchedColumns() []*MatchedColumn {
	if x != nil {
		return x.MatchedColumns
	}
	return nil
}

var File_go_protos_column_matcher_proto protoreflect.FileDescriptor

var file_go_protos_column_matcher_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72,
	0x22, 0x62, 0x0a, 0x14, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x73, 0x76, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x73, 0x76, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x22, 0x57, 0x0a, 0x0d, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x43,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x73, 0x76, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x73, 0x76, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0x5f, 0x0a,
	0x15, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x64, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72,
	0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x0e,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x32, 0x6c,
	0x0a, 0x0d, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x12,
	0x5b, 0x0a, 0x0c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12,
	0x24, 0x2e, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72,
	0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_go_protos_column_matcher_proto_rawDescOnce sync.Once
	file_go_protos_column_matcher_proto_rawDescData = file_go_protos_column_matcher_proto_rawDesc
)

func file_go_protos_column_matcher_proto_rawDescGZIP() []byte {
	file_go_protos_column_matcher_proto_rawDescOnce.Do(func() {
		file_go_protos_column_matcher_proto_rawDescData = protoimpl.X.CompressGZIP(file_go_protos_column_matcher_proto_rawDescData)
	})
	return file_go_protos_column_matcher_proto_rawDescData
}

var file_go_protos_column_matcher_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_go_protos_column_matcher_proto_goTypes = []interface{}{
	(*ColumnMatcherRequest)(nil),  // 0: column_matcher.ColumnMatcherRequest
	(*MatchedColumn)(nil),         // 1: column_matcher.MatchedColumn
	(*ColumnMatcherResponse)(nil), // 2: column_matcher.ColumnMatcherResponse
}
var file_go_protos_column_matcher_proto_depIdxs = []int32{
	1, // 0: column_matcher.ColumnMatcherResponse.matched_columns:type_name -> column_matcher.MatchedColumn
	0, // 1: column_matcher.ColumnMatcher.MatchColumns:input_type -> column_matcher.ColumnMatcherRequest
	2, // 2: column_matcher.ColumnMatcher.MatchColumns:output_type -> column_matcher.ColumnMatcherResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_go_protos_column_matcher_proto_init() }
func file_go_protos_column_matcher_proto_init() {
	if File_go_protos_column_matcher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_go_protos_column_matcher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnMatcherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_protos_column_matcher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchedColumn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_protos_column_matcher_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnMatcherResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_go_protos_column_matcher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_protos_column_matcher_proto_goTypes,
		DependencyIndexes: file_go_protos_column_matcher_proto_depIdxs,
		MessageInfos:      file_go_protos_column_matcher_proto_msgTypes,
	}.Build()
	File_go_protos_column_matcher_proto = out.File
	file_go_protos_column_matcher_proto_rawDesc = nil
	file_go_protos_column_matcher_proto_goTypes = nil
	file_go_protos_column_matcher_proto_depIdxs = nil
}
